// Auto-generated registry of every numeric slider that flows through the
// draw pipeline's P object, used by the audio modulation panel (Audio tab)
// to let the user bind ANY slider to an audio band by name, instead of
// retrofitting a bind-icon onto each of the ~130 individual slider rows
// across GradientsTab.tsx/EffectsTab.tsx. Applied generically in
// useCanvasDraw.ts by adding to drawCtx[param] before the draw call, so it
// works for every entry here without per-slider wiring.
export interface ModulatableParam {
  key: string;
  label: string;
  min: number;
  max: number;
}

export const MODULATABLE_PARAMS: ModulatableParam[] = [
  { key: 'angleCenterX', label: 'Angle Center X', min: 0.0, max: 100.0 },
  { key: 'angleCenterY', label: 'Angle Center Y', min: 0.0, max: 100.0 },
  { key: 'angleStartOffset', label: 'Angle Start Offset', min: 0.0, max: 360.0 },
  { key: 'asciiSize', label: 'Ascii Size', min: 6.0, max: 40.0 },
  { key: 'attractorDotSize', label: 'Attractor Size', min: 0.5, max: 6.0 },
  { key: 'attractorPointCount', label: 'Points', min: 1.0, max: 20.0 },
  { key: 'attractorScale', label: 'Attractor Scale', min: 0.3, max: 3.0 },
  { key: 'attractorSpeed', label: 'Attractor Speed', min: 0.1, max: 5.0 },
  { key: 'attractorTrailFade', label: 'Fade', min: 0.01, max: 0.3 },
  { key: 'auroraBandCount', label: 'Aurora Bands', min: 2.0, max: 12.0 },
  { key: 'auroraBandHeight', label: 'Band Height', min: 0.5, max: 4.0 },
  { key: 'auroraWaveSpeed', label: 'Aurora Speed', min: 0.1, max: 3.0 },
  { key: 'bloomIntensity', label: 'Bloom Intensity', min: 0.0, max: 2.0 },
  { key: 'bloomRadius', label: 'Bloom Radius', min: 2.0, max: 40.0 },
  { key: 'blurGaussianAmount', label: 'Blur Gaussian Amount', min: 1.0, max: 50.0 },
  { key: 'blurMotionAmount', label: 'Blur Motion Amount', min: 1.0, max: 50.0 },
  { key: 'blurMotionDirection', label: 'Blur Motion Direction', min: 0.0, max: 360.0 },
  { key: 'blurRadialAmount', label: 'Blur Radial Amount', min: 1.0, max: 50.0 },
  { key: 'causticsBrightness', label: 'Brightness', min: 0.5, max: 5.0 },
  { key: 'causticsScale', label: 'Caustics Scale', min: 1.0, max: 12.0 },
  { key: 'chromaticAngle', label: 'Chromatic Angle', min: 0.0, max: 360.0 },
  { key: 'chromaticOffset', label: 'Chromatic Offset', min: 1.0, max: 200.0 },
  { key: 'chromaticTrailsDecay', label: 'Chromatic Trails Decay', min: 0.5, max: 0.99 },
  { key: 'chromaticTrailsOffset', label: 'Chromatic Trails Offset', min: 1.0, max: 30.0 },
  { key: 'colorShiftHue', label: 'Color Shift Hue', min: 0.0, max: 255.0 },
  { key: 'concentricRingCount', label: 'Concentric Ring Count', min: 1.0, max: 30.0 },
  { key: 'concentricRingWidth', label: 'Concentric Ring Width', min: 10.0, max: 300.0 },
  { key: 'ditherLevels', label: 'Dither Levels', min: 2.0, max: 16.0 },
  { key: 'duotoneIntensity', label: 'Duotone Intensity', min: 0.0, max: 1.0 },
  { key: 'dustCrackleIntensity', label: 'Dust Crackle Intensity', min: 0.0, max: 1.0 },
  { key: 'emojiRotateSpeed', label: 'Emoji Rotate Speed', min: 0.0, max: 180.0 },
  { key: 'emojiSize', label: 'Emoji Size', min: 10.0, max: 60.0 },
  { key: 'emojiSizeVariation', label: 'Emoji Size Variation', min: 0.0, max: 100.0 },
  { key: 'fadeDirection', label: 'Fade Direction', min: 0.0, max: 360.0 },
  { key: 'feedbackDecay', label: 'Feedback Decay', min: 0.5, max: 0.97 },
  { key: 'feedbackZoom', label: 'Feedback Zoom', min: 0.0, max: 5.0 },
  { key: 'fisheyeCenterX', label: 'Fisheye Center X', min: 0.0, max: 100.0 },
  { key: 'fisheyeCenterY', label: 'Fisheye Center Y', min: 0.0, max: 100.0 },
  { key: 'fisheyeStrength', label: 'Fisheye Strength', min: 0.0, max: 10.0 },
  { key: 'flowParticleCount', label: 'Particles', min: 20.0, max: 800.0 },
  { key: 'flowScale', label: 'Flow Scale', min: 0.5, max: 10.0 },
  { key: 'flowSpeed', label: 'Flow Speed', min: 0.1, max: 5.0 },
  { key: 'flowThickness', label: 'Flow Thickness', min: 0.5, max: 6.0 },
  { key: 'flowerCircles', label: 'Flower Circles', min: 1.0, max: 12.0 },
  { key: 'flowerScale', label: 'Flower Scale', min: 0.1, max: 3.0 },
  { key: 'flowerSpread', label: 'Flower Spread', min: 0.3, max: 2.5 },
  { key: 'glitchBlockSize', label: 'Glitch Block Size', min: 4.0, max: 80.0 },
  { key: 'glitchChromaSplit', label: 'Glitch Chroma Split', min: 0.0, max: 20.0 },
  { key: 'glitchIntensity', label: 'Glitch Intensity', min: 0.05, max: 1.0 },
  { key: 'grainIntensity', label: 'Grain Intensity', min: 0.0, max: 1.0 },
  { key: 'gridColumns', label: 'Grid Columns', min: 2.0, max: 50.0 },
  { key: 'gridRows', label: 'Grid Rows', min: 2.0, max: 50.0 },
  { key: 'gridSides', label: 'Grid Sides', min: 1.0, max: 10.0 },
  { key: 'gridVariation', label: 'Grid Variation', min: 0.0, max: 1.0 },
  { key: 'halftoneSize', label: 'Halftone Size', min: 2.0, max: 200.0 },
  { key: 'halftoneVariation', label: 'Halftone Variation', min: 0.0, max: 1.0 },
  { key: 'helixTightness', label: 'Helix Tightness', min: 0.1, max: 2.0 },
  { key: 'helixTurns', label: 'Helix Turns', min: 1.0, max: 20.0 },
  { key: 'invertAmount', label: 'Invert Amount', min: 0.0, max: 1.0 },
  { key: 'iridescentIntensity', label: 'Iridescent Intensity', min: 0.1, max: 2.0 },
  { key: 'iridescentScale', label: 'Iridescent Scale', min: 0.1, max: 10.0 },
  { key: 'juliaIterations', label: 'Julia Detail', min: 20.0, max: 120.0 },
  { key: 'juliaZoom', label: 'Zoom', min: 0.3, max: 3.0 },
  { key: 'kaleidoscopeRotateSpeed', label: 'Kaleidoscope Rotate Speed', min: 0.0, max: 5.0 },
  { key: 'kaleidoscopeSegments', label: 'Kaleidoscope Segments', min: 2.0, max: 50.0 },
  { key: 'lavaBlobCount', label: 'Blobs', min: 2.0, max: 12.0 },
  { key: 'lavaBlobSize', label: 'Blob Size', min: 0.05, max: 0.4 },
  { key: 'liquidScale', label: 'Liquid Scale', min: 0.5, max: 10.0 },
  { key: 'liquidStrength', label: 'Liquid Strength', min: 0.0, max: 100.0 },
  { key: 'marbleOctaves', label: 'Marble Detail', min: 1.0, max: 8.0 },
  { key: 'marbleTurbulence', label: 'Turbulence', min: 0.0, max: 5.0 },
  { key: 'marbleVeinFreq', label: 'Vein Freq', min: 0.5, max: 10.0 },
  { key: 'meshGridSize', label: 'Mesh Grid Size', min: 1.0, max: 10.0 },
  { key: 'meshJitter', label: 'Mesh Jitter', min: 0.0, max: 100.0 },
  { key: 'metaballCount', label: 'Count', min: 2.0, max: 14.0 },
  { key: 'metaballSize', label: 'Metaball Size', min: 0.05, max: 0.4 },
  { key: 'metaballSpeed', label: 'Metaball Speed', min: 0.1, max: 5.0 },
  { key: 'mirrorTileCount', label: 'Mirror Tile Count', min: 2.0, max: 16.0 },
  { key: 'moireOffset', label: 'Offset', min: 0.0, max: 100.0 },
  { key: 'moireScale', label: 'Moire Scale', min: 3.0, max: 40.0 },
  { key: 'moireSpeed', label: 'Moire Speed', min: 0.1, max: 5.0 },
  { key: 'noiseDirection', label: 'Noise Direction', min: 0.0, max: 360.0 },
  { key: 'noiseOctaves', label: 'Noise Octaves', min: 1.0, max: 8.0 },
  { key: 'noiseScale', label: 'Noise Scale', min: 10.0, max: 200.0 },
  { key: 'noiseWarp', label: 'Noise Warp', min: 0.0, max: 1.0 },
  { key: 'photoOpacity', label: 'Photo Opacity', min: 0.0, max: 100.0 },
  { key: 'pixelSize', label: 'Pixel Size', min: 5.0, max: 200.0 },
  { key: 'plasmaComplexity', label: 'Plasma Complexity', min: 1.0, max: 10.0 },
  { key: 'plasmaZoomScale', label: 'Plasma Zoom Scale', min: 0.1, max: 5.0 },
  { key: 'polygon2Sides', label: 'Polygon2 Sides', min: 1.0, max: 24.0 },
  { key: 'posterizeLevels', label: 'Posterize Levels', min: 2.0, max: 16.0 },
  { key: 'radarBeamWidth', label: 'Radar Beam Width', min: 1.0, max: 90.0 },
  { key: 'radarFadeLength', label: 'Radar Fade Length', min: 10.0, max: 180.0 },
  { key: 'radialBurstCount', label: 'Radial Burst Count', min: 3.0, max: 16.0 },
  { key: 'radialBurstSize', label: 'Radial Burst Size', min: 10.0, max: 200.0 },
  { key: 'radialBurstSpread', label: 'Radial Burst Spread', min: 10.0, max: 100.0 },
  { key: 'radialSizeScale', label: 'Radial Size Scale', min: 0.25, max: 4.0 },
  { key: 'reactionDiffusionFeed', label: 'Feed Rate', min: 0.02, max: 0.08 },
  { key: 'reactionDiffusionKill', label: 'Kill Rate', min: 0.04, max: 0.07 },
  { key: 'reactionDiffusionSpeed', label: 'Reaction Diffusion Speed', min: 0.2, max: 3.0 },
  { key: 'rippleAmplitude', label: 'Ripple Amplitude', min: 5.0, max: 50.0 },
  { key: 'scanlineIntensity', label: 'Scanline Intensity', min: 0.0, max: 1.0 },
  { key: 'scanlineSpacing', label: 'Scanline Spacing', min: 2.0, max: 20.0 },
  { key: 'scanlineSpeed', label: 'Scanline Speed', min: 0.0, max: 5.0 },
  { key: 'shapesCount', label: 'Shapes Count', min: 1.0, max: 50.0 },
  { key: 'shapesSides', label: 'Shapes Sides', min: 1.0, max: 10.0 },
  { key: 'slitScanIntensity', label: 'Slit Scan Intensity', min: 0.1, max: 10.0 },
  { key: 'topographicBands', label: 'Topographic Bands', min: 3.0, max: 30.0 },
  { key: 'topographicLineWidth', label: 'Line Width', min: 0.01, max: 0.15 },
  { key: 'topographicScale', label: 'Topographic Scale', min: 10.0, max: 100.0 },
  { key: 'triangleSize', label: 'Triangle Size', min: 10.0, max: 200.0 },
  { key: 'truchetSize', label: 'Tile Size', min: 15.0, max: 100.0 },
  { key: 'truchetThickness', label: 'Truchet Thickness', min: 1.0, max: 15.0 },
  { key: 'truchetVariation', label: 'Variation', min: 0.0, max: 1.0 },
  { key: 'vhsGlitchIntensity', label: 'Vhs Glitch Intensity', min: 0.0, max: 1.0 },
  { key: 'vignetteSoftness', label: 'Vignette Softness', min: 0.0, max: 100.0 },
  { key: 'vignetteStrength', label: 'Vignette Strength', min: 0.0, max: 1.0 },
  { key: 'voronoiCellCount', label: 'Voronoi Cell Count', min: 3.0, max: 30.0 },
  { key: 'voronoiDistortion', label: 'Voronoi Distortion', min: 0.0, max: 100.0 },
  { key: 'waveAmplitude', label: 'Wave Amplitude', min: 10.0, max: 200.0 },
  { key: 'waveDistortionRotation', label: 'Wave Distortion Rotation', min: 0.0, max: 360.0 },
  { key: 'waveDistortionStrength', label: 'Wave Distortion Strength', min: 5.0, max: 100.0 },
  { key: 'waveFrequency', label: 'Wave Frequency', min: 1.0, max: 10.0 },
  { key: 'waveNumber', label: 'Wave Number', min: 1.0, max: 20.0 },
  { key: 'waveRotation', label: 'Wave Rotation', min: 0.0, max: 360.0 },
  { key: 'windmillRotations', label: 'Windmill Rotations', min: 1.0, max: 10.0 },
  { key: 'windmillThickness', label: 'Windmill Thickness', min: 5.0, max: 100.0 },
  { key: 'windmillTightness', label: 'Windmill Tightness', min: 1.0, max: 20.0 },
];

