import { getScratchCanvas } from '../../utils/scratchCanvas';

export function applyFeedback(P: any): void {
  const {
    activeEffects,
    addGradientStops,
    angleCenterX,
    angleCenterY,
    angleStartOffset,
    asciiChars,
    asciiColor,
    asciiSize,
    attractorAnimTime,
    attractorBufferRef,
    attractorPointCount,
    attractorPointsRef,
    attractorScale,
    audioMidsLevel,
    audioSubBassLevel,
    audioTrebleLevel,
    auroraAnimTime,
    auroraBandCount,
    auroraBandHeight,
    auroraWaveSpeed,
    bassThreshold,
    bloomIntensity,
    bloomRadius,
    blurGaussianAmount,
    blurMotionAmount,
    blurMotionDirection,
    blurRadialAmount,
    blurType,
    canvasRef,
    causticsAnimTime,
    causticsBrightness,
    causticsScale,
    charcoalIntensity,
    chromaticAngle,
    chromaticOffset,
    chromaticTrailsBufferRef,
    chromaticTrailsDecay,
    chromaticTrailsOffset,
    colorPins,
    colorShiftHue,
    concentricRingCount,
    concentricRingWidth,
    helixTightness,
    helixTurns,
    ditherLevels,
    ditherType,
    drawParams,
    glitchIntensity,
    glitchBlockSize,
    glitchChromaSplit,
    drawParamsDirtyRef,
    drawRef,
    duotoneColor1,
    duotoneColor2,
    duotoneColor3,
    duotoneIntensity,
    duotoneThreeColor,
    dustCrackleIntensity,
    emojiAnimTime,
    emojiChars,
    emojiOffsetX,
    emojiSize,
    emojiSizeVariation,
    fadeDirection,
    feedbackBufferRef,
    feedbackDecay,
    feedbackRotation,
    feedbackZoom,
    fisheyeCenterX,
    fisheyeCenterY,
    fisheyeStrength,
    flowAnimTime,
    flowBufferRef,
    flowParticleCount,
    flowParticlesRef,
    flowScale,
    flowThickness,
    flowerAnimTime,
    flowerCircles,
    flowerRotation,
    flowerScale,
    flowerSpread,
    gradientAngle,
    gradientAngleRef,
    gradientColors,
    gradientColorsRef,
    gradientType,
    grainIntensity,
    grainType,
    gridColumns,
    gridRotation,
    gridRows,
    gridShapeSize,
    gridSides,
    gridVariation,
    halftoneCMYK,
    halftoneMove,
    halftoneSize,
    halftoneTimeRef,
    halftoneVariation,
    iridescentAngle,
    iridescentIntensity,
    iridescentScale,
    isAudioEnabled,
    isAudioReactive,
    isAutoModeRef,
    isVCRPlayingRef,
    kaleidoAngleRef,
    kaleidoscopeRotateSpeed,
    kaleidoscopeSegments,
    lavaAnimTime,
    lavaBlobCount,
    lavaBlobSize,
    lavaSpeed,
    liquidAnimTime,
    liquidScale,
    liquidStrength,
    marbleAnimTime,
    marbleOctaves,
    marbleTurbulence,
    marbleVeinFreq,
    meshGridSize,
    meshJitter,
    metaballAnimTime,
    metaballCount,
    metaballSize,
    mirrorMode,
    mirrorTileCount,
    moireAnimTime,
    moireOffset,
    moireScale,
    noiseDirection,
    noiseOctaves,
    noiseScale,
    noiseType,
    noiseWarp,
    photoBlendMode,
    photoImageRef,
    photoOpacity,
    pixelSize,
    plasmaComplexity,
    plasmaZoomScale,
    polygon2Sides,
    posterizeLevels,
    radarBeamWidth,
    radarFadeLength,
    radarSweepAngle,
    radialBurstCount,
    radialBurstSize,
    radialBurstSpread,
    radialSizeScale,
    reactionDiffusionFeed,
    reactionDiffusionGridRef,
    reactionDiffusionKill,
    reactionDiffusionSpeed,
    resolutionMultiplier,
    scanlineIntensity,
    scanlineSpacing,
    scanlineSpeed,
    shapesCount,
    shapesSides,
    slitScanBufferRef,
    slitScanDirection,
    slitScanIntensity,
    windmillRotations,
    windmillThickness,
    windmillTightness,
    windmillZoom,
    triangleSize,
    topographicBands,
    topographicLineWidth,
    topographicScale,
    juliaReal,
    juliaImaginary,
    juliaZoom,
    juliaIterations,
    juliaCanvasRef,
    truchetSize,
    truchetThickness,
    truchetVariation,
    vhsGlitchIntensity,
    vignetteSoftness,
    vignetteStrength,
    voronoiAnimTime,
    voronoiCellCount,
    voronoiDistortion,
    waveAmplitude,
    waveDistortionRotation,
    waveDistortionStrength,
    waveFrequency,
    waveNumberRef,
    waveRotationRef,
    waveScale,
    zoom,
    zoomRef,
    ctx,
    canvas,
    centerX,
    centerY,
    maxRadius,
    fitRadius,
    angleRad,
    cosAngle,
    sinAngle,
    displayWidth,
    displayHeight,
    putScaledImageData,
    getDisplayImageData,
    effectType,
    index,
    isFirstEffect,
    audioModulation,
    imageData
  } = P;
            // Trails: composite previous frame (zoomed+rotated+faded) behind current
            const fbTmp = getScratchCanvas('feedbackTmp', displayWidth, displayHeight);
            const fbTmpCtx = fbTmp.getContext('2d');
            if (fbTmpCtx) fbTmpCtx.drawImage(canvas, 0, 0, displayWidth, displayHeight); // snapshot current

            const fb = feedbackBufferRef.current;
            if (fb && fb.width === displayWidth && fb.height === displayHeight) {
              const audioFbDecay = isAudioReactive
                ? Math.min(0.98, feedbackDecay + audioSubBassLevel / 5 * 0.08)
                : feedbackDecay;
              const audioFbZoom = feedbackZoom * (1 + (isAudioReactive ? audioSubBassLevel / 5 * 0.3 : 0));
              // Clear canvas and draw feedback behind current frame
              ctx.clearRect(0, 0, displayWidth, displayHeight);
              ctx.save();
              ctx.globalAlpha = Math.min(0.98, audioFbDecay);
              ctx.translate(centerX, centerY);
              // Rotation/zoom multipliers bumped 4x — at the old scale the sliders'
              // full range barely moved the trail per frame, reading as inert.
              ctx.rotate(feedbackRotation * 0.02);
              const zs = 1 + audioFbZoom * 0.02;
              ctx.scale(zs, zs);
              ctx.translate(-centerX, -centerY);
              ctx.drawImage(fb, 0, 0);
              ctx.restore();
              // Blend the current (fully opaque) frame over the trail instead of a
              // plain source-over draw — at alpha 1 that would completely erase the
              // trail underneath every frame, which is why no trail was ever visible.
              // 'lighten' lets the brighter of (trail, current) win per-pixel so the
              // decaying echo actually shows through.
              ctx.globalAlpha = 1;
              ctx.globalCompositeOperation = 'lighten';
              ctx.drawImage(fbTmp, 0, 0);
              ctx.globalCompositeOperation = 'source-over';
            }
            // Update feedback buffer
            if (!feedbackBufferRef.current || feedbackBufferRef.current.width !== displayWidth) {
              feedbackBufferRef.current = document.createElement('canvas');
              feedbackBufferRef.current.width = displayWidth;
              feedbackBufferRef.current.height = displayHeight;
            }
            const updateCtx = feedbackBufferRef.current.getContext('2d');
            if (updateCtx) { updateCtx.clearRect(0, 0, displayWidth, displayHeight); updateCtx.drawImage(canvas, 0, 0, displayWidth, displayHeight); }
}
