// Module-level clock — same cosmetic-phase-only tradeoff as the other
// generative effects (see applyTriangleField.ts).
let agTime = 0;

export function applyAuraGlow(P: any): void {
  const {
    activeEffects,
    addGradientStops,
    angleCenterX,
    angleCenterY,
    angleStartOffset,
    asciiChars,
    asciiColor,
    asciiSize,
    attractorAnimTime,
    attractorBufferRef,
    attractorPointCount,
    attractorPointsRef,
    attractorScale,
    audioMidsLevel,
    audioSubBassLevel,
    audioTrebleLevel,
    auraGlowCount,
    auraGlowSpeed,
    auraGlowOpacity,
    auroraAnimTime,
    auroraBandCount,
    auroraBandHeight,
    auroraWaveSpeed,
    bassThreshold,
    bloomIntensity,
    bloomRadius,
    blurGaussianAmount,
    blurMotionAmount,
    blurMotionDirection,
    blurRadialAmount,
    blurType,
    canvasRef,
    causticsAnimTime,
    causticsBrightness,
    causticsScale,
    charcoalIntensity,
    chromaticAngle,
    chromaticOffset,
    chromaticTrailsBufferRef,
    chromaticTrailsDecay,
    chromaticTrailsOffset,
    colorPins,
    colorShiftHue,
    concentricRingCount,
    concentricRingWidth,
    helixTightness,
    helixTurns,
    ditherLevels,
    ditherType,
    drawParams,
    glitchIntensity,
    glitchBlockSize,
    glitchChromaSplit,
    drawParamsDirtyRef,
    drawRef,
    duotoneColor1,
    duotoneColor2,
    duotoneColor3,
    duotoneIntensity,
    duotoneThreeColor,
    dustCrackleIntensity,
    emojiAnimTime,
    emojiChars,
    emojiOffsetX,
    emojiSize,
    emojiSizeVariation,
    fadeDirection,
    feedbackBufferRef,
    feedbackDecay,
    feedbackRotation,
    feedbackZoom,
    fisheyeCenterX,
    fisheyeCenterY,
    fisheyeStrength,
    flowAnimTime,
    flowBufferRef,
    flowParticleCount,
    flowParticlesRef,
    flowScale,
    flowThickness,
    flowerAnimTime,
    flowerCircles,
    flowerRotation,
    flowerScale,
    flowerSpread,
    gradientAngle,
    gradientAngleRef,
    gradientColors,
    gradientColorsRef,
    gradientType,
    grainIntensity,
    grainType,
    gridColumns,
    gridRotation,
    gridRows,
    gridShapeSize,
    gridSides,
    gridVariation,
    halftoneCMYK,
    halftoneMove,
    halftoneSize,
    halftoneTimeRef,
    halftoneVariation,
    iridescentAngle,
    iridescentIntensity,
    iridescentScale,
    isAudioEnabled,
    isAudioReactive,
    isAutoModeRef,
    isVCRPlayingRef,
    kaleidoAngleRef,
    kaleidoscopeRotateSpeed,
    kaleidoscopeSegments,
    lavaAnimTime,
    lavaBlobCount,
    lavaBlobSize,
    lavaSpeed,
    liquidAnimTime,
    liquidScale,
    liquidStrength,
    marbleAnimTime,
    marbleOctaves,
    marbleTurbulence,
    marbleVeinFreq,
    metaballAnimTime,
    metaballCount,
    metaballSize,
    mirrorMode,
    mirrorTileCount,
    moireAnimTime,
    moireOffset,
    moireScale,
    noiseDirection,
    noiseOctaves,
    noiseScale,
    noiseType,
    noiseWarp,
    photoBlendMode,
    photoImageRef,
    photoOpacity,
    pixelSize,
    plasmaComplexity,
    plasmaZoomScale,
    polygon2Sides,
    posterizeLevels,
    radarBeamWidth,
    radarFadeLength,
    radarSweepAngle,
    radialBurstCount,
    radialBurstSize,
    radialBurstSpread,
    radialSizeScale,
    reactionDiffusionFeed,
    reactionDiffusionGridRef,
    reactionDiffusionKill,
    reactionDiffusionSpeed,
    resolutionMultiplier,
    scanlineIntensity,
    scanlineSpacing,
    scanlineSpeed,
    shapesCount,
    shapesSides,
    slitScanBufferRef,
    slitScanDirection,
    slitScanIntensity,
    windmillRotations,
    windmillThickness,
    windmillTightness,
    windmillZoom,
    triangleSize,
    topographicBands,
    topographicLineWidth,
    topographicScale,
    juliaReal,
    juliaImaginary,
    juliaZoom,
    juliaIterations,
    juliaCanvasRef,
    truchetSize,
    truchetThickness,
    truchetVariation,
    vhsGlitchIntensity,
    vignetteSoftness,
    vignetteStrength,
    voronoiAnimTime,
    voronoiCellCount,
    voronoiDistortion,
    waveAmplitude,
    waveDistortionRotation,
    waveDistortionStrength,
    waveFrequency,
    waveNumberRef,
    waveRotationRef,
    waveScale,
    zoom,
    zoomRef,
    ctx,
    canvas,
    centerX,
    centerY,
    maxRadius,
    fitRadius,
    angleRad,
    cosAngle,
    sinAngle,
    displayWidth,
    displayHeight,
    putScaledImageData,
    getDisplayImageData,
    effectType,
    index,
    isFirstEffect,
    audioModulation,
  } = P;
  // Generative overlay: a handful of soft colored light sources drift
  // around the canvas on independent Lissajous-style paths, drawn as
  // native radial gradients (no per-pixel loop — cheap, same technique
  // Aurora/Fade already use for the base gradient layer) and blended in
  // via 'screen'. Distinct from Duotone/Chromatic/Posterize, which all
  // remap the existing frame's own colors: this paints its own light
  // instead of recoloring what's there.
  //
  // 'screen' (not 'lighten') and a larger radius: 'lighten' only ever
  // keeps the brighter of source/destination per channel, so a single
  // light source barely reads as more than a soft tint on top of an
  // already-bright base gradient. 'screen' — 1-(1-a)(1-b) — actually
  // brightens the result the way overlapping real light does, which is
  // what "more intense" here actually means.
  if (canvas.width === 0 || canvas.height === 0) return;

  const agAudioActive = isFirstEffect && isAudioReactive;
  agTime += 0.006 * auraGlowSpeed * (agAudioActive ? 1 + audioTrebleLevel * 0.5 : 1);

  const count = Math.max(1, Math.round(auraGlowCount));
  const colorCount = gradientColors?.length || 1;
  const baseRadius = Math.min(displayWidth, displayHeight) * (0.42 + (agAudioActive ? audioSubBassLevel * 0.2 : 0));
  const opacity = Math.max(0, Math.min(1, auraGlowOpacity));

  ctx.save();
  ctx.globalCompositeOperation = 'screen';
  ctx.globalAlpha = opacity;
  for (let i = 0; i < count; i++) {
    const phase = i * 2.4;
    const x = displayWidth / 2 + Math.sin(agTime * 0.7 + phase) * displayWidth * 0.32;
    const y = displayHeight / 2 + Math.cos(agTime * 0.5 + phase * 1.3) * displayHeight * 0.32;
    const color = gradientColors?.[i % colorCount] ?? { r: 255, g: 255, b: 255 };
    const grad = ctx.createRadialGradient(x, y, 0, x, y, baseRadius);
    grad.addColorStop(0, `rgba(${color.r | 0}, ${color.g | 0}, ${color.b | 0}, 1)`);
    grad.addColorStop(1, `rgba(${color.r | 0}, ${color.g | 0}, ${color.b | 0}, 0)`);
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, displayWidth, displayHeight);
  }
  ctx.restore();
}
