// Circuit: glowing branching paths radiating from center, drawn as vector
// strokes (not per-pixel imageData like the other new gradients) with a
// bright pulse traveling outward along each branch. The branch structure is
// generated by a seeded PRNG keyed off branchCount/maxDepth so it stays
// stable frame to frame -- only the pulse position and glow animate via
// circuitAnimTime, since re-rolling Math.random() every frame would make
// the whole structure flicker instead of read as a fixed circuit board.
function mulberry32(seed: number) {
  let a = seed;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

interface Segment {
  x1: number; y1: number; x2: number; y2: number;
  depth: number; cumDist: number; branchLen: number; colorIdx: number;
}

export function drawCircuit(P: any): CanvasGradient | undefined {
  const {
    ctx, centerX, centerY, displayWidth, displayHeight,
    gradientColors, circuitAnimTime, circuitBranchCount, circuitMaxDepth, circuitGlowIntensity,
    isAudioEnabled, isAudioReactive, audioSubBassLevel, audioTrebleLevel,
  } = P;

  const audioActive = isAudioEnabled && isAudioReactive;
  const glowBoost = audioActive ? 1 + (audioSubBassLevel / 5) * 0.8 : 1;
  const pulseSpeedBoost = audioActive ? 1 + (audioTrebleLevel / 5) * 1.5 : 1;

  const branchCount = Math.max(3, Math.min(Math.round(circuitBranchCount), 10));
  const maxDepth = Math.max(2, Math.min(Math.round(circuitMaxDepth), 7));
  const seed = branchCount * 100003 + maxDepth * 733;
  const rng = mulberry32(seed);

  const baseLen = Math.min(displayWidth, displayHeight) * 0.16;
  const segments: Segment[] = [];

  const grow = (x: number, y: number, angle: number, depth: number, length: number, cumDist: number, colorIdx: number) => {
    if (depth > maxDepth || length < 6) return;
    const steps = 3 + Math.floor(rng() * 3);
    let cx = x, cy = y, dist = cumDist;
    for (let s = 0; s < steps; s++) {
      const jitter = (rng() - 0.5) * 0.55;
      const a = angle + jitter;
      const segLen = length / steps;
      const nx = cx + Math.cos(a) * segLen;
      const ny = cy + Math.sin(a) * segLen;
      dist += segLen;
      segments.push({ x1: cx, y1: cy, x2: nx, y2: ny, depth, cumDist: dist, branchLen: length, colorIdx });
      cx = nx; cy = ny;
      angle = a;
    }
    if (rng() < 0.75 - depth * 0.08) {
      grow(cx, cy, angle + (rng() < 0.5 ? 1 : -1) * (0.6 + rng() * 0.7), depth + 1, length * 0.68, dist, colorIdx);
    }
    if (depth < 2 || rng() < 0.35) {
      grow(cx, cy, angle - (rng() < 0.5 ? 1 : -1) * (0.4 + rng() * 0.6), depth + 1, length * 0.6, dist, colorIdx);
    }
  };

  for (let i = 0; i < branchCount; i++) {
    const angle = (i / branchCount) * Math.PI * 2 + rng() * 0.3;
    grow(centerX, centerY, angle, 0, baseLen, 0, i % gradientColors.length);
  }

  ctx.fillStyle = '#050608';
  ctx.fillRect(0, 0, displayWidth, displayHeight);

  const t = circuitAnimTime * pulseSpeedBoost;
  const pulseWindow = 60;

  for (const seg of segments) {
    const color = gradientColors[seg.colorIdx] || { r: 100, g: 220, b: 255 };
    const pulsePos = (t * 140 + seg.colorIdx * 400) % (seg.branchLen + 400);
    const distFromPulse = Math.abs(seg.cumDist - pulsePos);
    const pulseT = Math.max(0, 1 - distFromPulse / pulseWindow);

    const baseAlpha = 0.35;
    const alpha = baseAlpha + pulseT * 0.65;
    const width = 1.2 + pulseT * 1.8;

    ctx.strokeStyle = `rgba(${color.r}, ${color.g}, ${color.b}, ${alpha})`;
    ctx.lineWidth = width;
    ctx.shadowBlur = (4 + pulseT * 16) * circuitGlowIntensity * glowBoost;
    ctx.shadowColor = `rgb(${color.r}, ${color.g}, ${color.b})`;
    ctx.beginPath();
    ctx.moveTo(seg.x1, seg.y1);
    ctx.lineTo(seg.x2, seg.y2);
    ctx.stroke();
  }
  ctx.shadowBlur = 0;

  return undefined;
}
