export function drawAurora(P: any): CanvasGradient | undefined {
  const {
    activeEffects,
    addGradientStops,
    angleCenterX,
    angleCenterY,
    angleStartOffset,
    asciiChars,
    asciiColor,
    asciiSize,
    attractorAnimTime,
    attractorBufferRef,
    attractorPointCount,
    attractorPointsRef,
    attractorScale,
    audioMidsLevel,
    audioSubBassLevel,
    audioTrebleLevel,
    auroraAnimTime,
    auroraBandCount,
    auroraBandHeight,
    auroraWaveSpeed,
    bassThreshold,
    bloomIntensity,
    bloomRadius,
    blurGaussianAmount,
    blurMotionAmount,
    blurMotionDirection,
    blurRadialAmount,
    blurType,
    canvasRef,
    causticsAnimTime,
    causticsBrightness,
    causticsScale,
    charcoalIntensity,
    chromaticAngle,
    chromaticOffset,
    chromaticTrailsBufferRef,
    chromaticTrailsDecay,
    chromaticTrailsOffset,
    colorPins,
    colorShiftHue,
    concentricRingCount,
    concentricRingWidth,
    helixTightness,
    helixTurns,
    ditherLevels,
    ditherType,
    drawParams,
    glitchIntensity,
    glitchBlockSize,
    glitchChromaSplit,
    drawParamsDirtyRef,
    drawRef,
    duotoneColor1,
    duotoneColor2,
    duotoneColor3,
    duotoneIntensity,
    duotoneThreeColor,
    dustCrackleIntensity,
    emojiAnimTime,
    emojiChars,
    emojiOffsetX,
    emojiSize,
    emojiSizeVariation,
    fadeDirection,
    feedbackBufferRef,
    feedbackDecay,
    feedbackRotation,
    feedbackZoom,
    fisheyeCenterX,
    fisheyeCenterY,
    fisheyeStrength,
    flowAnimTime,
    flowBufferRef,
    flowParticleCount,
    flowParticlesRef,
    flowScale,
    flowThickness,
    flowerAnimTime,
    flowerCircles,
    flowerRotation,
    flowerScale,
    flowerSpread,
    gradientAngle,
    gradientAngleRef,
    gradientColors,
    gradientColorsRef,
    gradientType,
    grainIntensity,
    grainType,
    gridColumns,
    gridRotation,
    gridRows,
    gridShapeSize,
    gridSides,
    gridVariation,
    halftoneCMYK,
    halftoneMove,
    halftoneSize,
    halftoneTimeRef,
    halftoneVariation,
    iridescentAngle,
    iridescentIntensity,
    iridescentScale,
    isAudioEnabled,
    isAudioReactive,
    isAutoModeRef,
    isVCRPlayingRef,
    kaleidoAngleRef,
    kaleidoscopeRotateSpeed,
    kaleidoscopeSegments,
    lavaAnimTime,
    lavaBlobCount,
    lavaBlobSize,
    lavaSpeed,
    liquidAnimTime,
    liquidScale,
    liquidStrength,
    marbleAnimTime,
    marbleOctaves,
    marbleTurbulence,
    marbleVeinFreq,
    meshGridSize,
    meshJitter,
    metaballAnimTime,
    metaballCount,
    metaballSize,
    mirrorMode,
    mirrorTileCount,
    moireAnimTime,
    moireOffset,
    moireScale,
    noiseDirection,
    noiseOctaves,
    noiseScale,
    noiseType,
    noiseWarp,
    photoBlendMode,
    photoImageRef,
    photoOpacity,
    pixelSize,
    plasmaComplexity,
    plasmaZoomScale,
    polygon2Sides,
    posterizeLevels,
    prevBassForRippleRef,
    radarBeamWidth,
    radarFadeLength,
    radarSweepAngle,
    radialBurstCount,
    radialBurstSize,
    radialBurstSpread,
    radialSizeScale,
    reactionDiffusionFeed,
    reactionDiffusionGridRef,
    reactionDiffusionKill,
    reactionDiffusionSpeed,
    resolutionMultiplier,
    rippleAmplitude,
    rippleAutoFrameRef,
    rippleRingsRef,
    scanlineIntensity,
    scanlineSpacing,
    scanlineSpeed,
    shapesCount,
    shapesSides,
    slitScanBufferRef,
    slitScanDirection,
    slitScanIntensity,
    windmillRotations,
    windmillThickness,
    windmillTightness,
    windmillZoom,
    triangleSize,
    topographicBands,
    topographicLineWidth,
    topographicScale,
    juliaReal,
    juliaImaginary,
    juliaZoom,
    juliaIterations,
    juliaCanvasRef,
    truchetSize,
    truchetThickness,
    truchetVariation,
    vhsGlitchIntensity,
    vignetteSoftness,
    vignetteStrength,
    voronoiAnimTime,
    voronoiCellCount,
    voronoiDistortion,
    waveAmplitude,
    waveDistortionRotation,
    waveDistortionStrength,
    waveFrequency,
    waveNumberRef,
    waveRotationRef,
    waveScale,
    zoom,
    zoomRef,
    ctx,
    canvas,
    centerX,
    centerY,
    maxRadius,
    fitRadius,
    angleRad,
    cosAngle,
    sinAngle,
    displayWidth,
    displayHeight,
    putScaledImageData,
    getDisplayImageData
  } = P;
  let gradient: CanvasGradient | undefined;
          ctx.fillStyle = '#000000';
          ctx.fillRect(0, 0, displayWidth, displayHeight);
          const auroraAudio = isAudioEnabled && isAudioReactive;
          const audioBassA = auroraAudio ? audioSubBassLevel / 5 : 0;   // 0-1
          const audioMidsA = auroraAudio ? audioMidsLevel / 5 : 0;
          const auroraTime = auroraAnimTime * (auroraWaveSpeed + audioMidsA * 4) + gradientAngle * 0.01;
          const auroraAudioBoost = 1 + audioBassA * 3.0;           // bands expand on bass
          const auroraWaveAmp  = 1 + audioBassA * 2.5;             // wave ripples harder
          const auroraAlphaBoost = 1 + audioBassA * 1.5;           // brightness flares
          const auroraColorShift = auroraAudio ? audioTrebleLevel * 0.8 : 0;
          const numBands = auroraBandCount;
          for (let b = 0; b < numBands; b++) {
            const bandY = (displayHeight * (b + 0.5)) / numBands;
            const bandHeight = (displayHeight / numBands) * auroraBandHeight * auroraAudioBoost;
            const colorIdx = ((b + Math.floor(auroraColorShift * gradientColors.length)) % gradientColors.length + gradientColors.length) % gradientColors.length;
            const color = gradientColors[colorIdx] || gradientColors[0];
            if (!color) continue;
            for (let x = 0; x < displayWidth; x++) {
              const nx = x / displayWidth;
              const wave = Math.sin(nx * 4 + auroraTime + b * 1.3) * 0.5 * auroraWaveAmp +
                           Math.sin(nx * 7 - auroraTime * 1.4 + b * 0.9) * 0.25 * auroraWaveAmp +
                           Math.sin(nx * 2 + auroraTime * 0.7) * 0.25;
              const cy = bandY + wave * bandHeight * 0.4;
              const nextColorIdx = ((colorIdx + 1) % gradientColors.length + gradientColors.length) % gradientColors.length;
              const nextColor = gradientColors[nextColorIdx] || color;
              const blend = (Math.sin(nx * Math.PI * 2 + auroraTime * 0.3 + b) * 0.5 + 0.5);
              const mixR = Math.round(color.r + (nextColor.r - color.r) * blend);
              const mixG = Math.round(color.g + (nextColor.g - color.g) * blend);
              const mixB = Math.round(color.b + (nextColor.b - color.b) * blend);
              const grad = ctx.createLinearGradient(x, cy - bandHeight * 0.5, x, cy + bandHeight * 0.5);
              const alpha = Math.min(1, (0.55 + Math.abs(wave) * 0.3) * auroraAlphaBoost);
              grad.addColorStop(0, `rgba(${mixR},${mixG},${mixB},0)`);
              grad.addColorStop(0.4, `rgba(${mixR},${mixG},${mixB},${alpha})`);
              grad.addColorStop(0.6, `rgba(${mixR},${mixG},${mixB},${alpha})`);
              grad.addColorStop(1, `rgba(${mixR},${mixG},${mixB},0)`);
              ctx.fillStyle = grad;
              ctx.fillRect(x, cy - bandHeight * 0.5, 1, bandHeight);
            }
          }
  return gradient;
}
